version: '3.8'

services:
  backend:
    container_name: backend_api
    build: .
    ports:
      - '3000:3000'
    networks:
      - backend
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: interview123
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - db-vol:/var/lib/mysql

networks:
  backend:

volumes:
  db-vol:
